[package]
name = "gpt_ui"
version = "0.0.1"
edition = "2021"

[dependencies]
gpt_core = { path = "../gpt_core" }
# error
snafu = { workspace = true }
# ui
crossterm = { version = "0.27.0", optional = true }
ratatui = { version = "0.26.3", optional = true }
clap = { version = "4.5.4", optional = true, features = ["derive"] }
dialoguer = { version = "0.11.0", optional = true, features = [] }
# async
tokio = { version = "1", features = ["full"] }

[features]
default = ["cli"]
mock = ["gpt_core/mock"]
cli = ["dep:clap", "dep:dialoguer"]
tui = ["dep:crossterm", "dep:ratatui"]
