[package]
name = "gpt_ui"
version = "0.0.1"
edition = "2021"

[dependencies]
gpt_core = { path = "../gpt_core", features = ["mock"] }
# error
snafu = { workspace = true }
# ui
crossterm = { version = "0.27.0", optional = true }
ratatui = { version = "0.26.3", optional = true }
clap = { version = "4.5.4", optional = true }

[features]
default = ["cli", "tui"]
cli = ["dep:clap"]
tui = ["dep:crossterm", "dep:ratatui"]
