[package]
name = "gpt_core"
version = "0.0.1-alpha3"
edition = "2021"

[package.metadata.docs.rs]
all-features = true

[dependencies]
# serde
serde = { workspace = true }
serde_json = { workspace = true }
# error
snafu = { workspace = true }
# tool
uuid = { version = "1.8.0", features = ["v7", "serde"] }
dirs = "2.0.0"
keyring = { version = "2.3.3" }
sanitize-filename = "0.5.0"
# net
reqwest = { version = "0.12.4", features = ["json", "stream"] }
url = { version = "2.5.0", features = ["serde"] }
# async
futures-util = "0.3.30"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros"] }

[build-dependencies]
rustc_version = "0.4.0"

[features]
default = []
mock = []
