[package]
name = "gpt_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }
uuid = { version = "1.8.0", features = ["v7", "serde"] }
reqwest = { version = "0.12.4", features = ["json", "stream"] }
tokio = { version = "1.0", features = ["full"] }
futures-util = "0.3.30"

[features]
default = ["mock"]
mock = []
