name: test

on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: extract-version
        run: echo "VERSION=$(grep -oP '^version = "\K[^"]+' Cargo.toml | awk '{$1=$1;print}')" >> $GITHUB_OUTPUT

      - name: Cache restore
        uses: actions/cache/restore@v4
        id: cache-cargo-restore
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ steps.extract-version.outputs.VERSION }}

      - name: install cargo components
        if: steps.cache-cargo-restore.outputs.cache-hit != 'true'
        run: rustup component add clippy

      - name: Run build
        if: steps.cache-cargo-restore.outputs.cache-hit != 'true'
        run: cargo build

      - name: Cache save
        if: steps.cache-cargo-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        id: cache-cargo-save
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ steps.cache-cargo-restore.outputs.cache-primary-key }}

      - name: run tests
        run: .github/scripts/test.sh
